[project]
name = "code_snippet_mcp_server"
version = "0.1.0"
description = "A sample Cloud Run MCP server requiring auth."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.3",
    "google-adk>=1.19.0",
    "python-dotenv>=1.0.0",
]
